# Generated by Django 4.0 on 2021-12-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='imagen',
            field=models.FileField(upload_to='media'),
        ),
    ]
