# Generated by Django 4.0 on 2021-12-19 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0002_alter_publicacion_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='destacado',
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='imagen',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
