# Generated by Django 3.2.9 on 2021-12-20 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0003_remove_publicacion_destacado_and_more'),
        ('publicacion', '0008_comentario_like'),
    ]

    operations = [
    ]
